# Generated by Django 4.2.4 on 2023-08-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('job_title', models.CharField(max_length=100)),
                ('programming_languages', models.TextField()),
                ('contact_info', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('portfolio', models.URLField(blank=True)),
            ],
        ),
    ]
