# Generated by Django 4.2.4 on 2023-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='ddinghub', max_length=255),
            preserve_default=False,
        ),
    ]
