# Generated by Django 4.2.4 on 2023-08-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
