# Generated by Django 4.2.4 on 2023-08-22 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0003_remove_userprofile_name_remove_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='call',
            field=models.CharField(default='010-1234-5678', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dream',
            field=models.TextField(default='programmer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.CharField(default='coding', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='introduce',
            field=models.TextField(default="Hello, I'm a software developer!"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default='developer', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages_tools',
            field=models.TextField(default='JAVA'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(default='convergence software', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='seo', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.URLField(default='URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tendency_MBTI',
            field=models.CharField(default='void', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tendency_personality',
            field=models.TextField(default='void'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tendency_worktime',
            field=models.CharField(default='night', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_message',
            field=models.TextField(default='rational'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='ESTJ', max_length=20),
        ),
    ]
