# Generated by Django 4.2.4 on 2023-08-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_remove_userprofile_nickname_alter_userprofile_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='nick', max_length=100),
            preserve_default=False,
        ),
    ]
