# Generated by Django 4.2 on 2023-08-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='viewCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
