# Generated by Django 4.2 on 2023-07-27 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gongmo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jickgoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jickgoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gongmo.jickgoon')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teamname', models.CharField(max_length=100, null=True)),
                ('call', models.CharField(max_length=100, null=True)),
                ('detail', models.TextField(null=True)),
                ('dev_capacity', models.PositiveIntegerField(default=0)),
                ('plan_capacity', models.PositiveIntegerField(default=0)),
                ('design_capacity', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gongmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gongmo.contest')),
                ('jickgoons', models.ManyToManyField(through='gongmo.Member', to='gongmo.jickgoon')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(null=True)),
                ('jickgoon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gongmo.jickgoon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gongmo.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gongmo.team'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gongmo.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
