# Generated by Django 4.2 on 2023-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='applicant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='team',
            field=models.TextField(null=True),
        ),
    ]
