# Generated by Django 4.2 on 2023-08-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0002_alter_team_tendency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
