# Generated by Django 4.2 on 2023-07-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0002_jickgoon_member_team_notification_member_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='gongmo',
            new_name='contest',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
