# Generated by Django 4.2 on 2023-08-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0002_alter_rejectedteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='viewCount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
