# Generated by Django 4.2 on 2023-08-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0003_contest_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='viewCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
