# Generated by Django 4.2 on 2023-07-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0003_rename_gongmo_team_contest_delete_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='design_capacity',
        ),
        migrations.RemoveField(
            model_name='team',
            name='dev_capacity',
        ),
        migrations.RemoveField(
            model_name='team',
            name='plan_capacity',
        ),
    ]
