# Generated by Django 4.2 on 2023-08-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0004_remove_team_design_capacity_remove_team_dev_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='design',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='dev',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='plan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
