# Generated by Django 4.2 on 2023-08-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0005_team_design_team_dev_team_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='jickgoon',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='jickgoon',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='team',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jickgoons',
        ),
        migrations.DeleteModel(
            name='Jickgoon',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
