# Generated by Django 4.2 on 2023-08-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0006_remove_member_jickgoon_remove_member_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jickgoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='design',
        ),
        migrations.RemoveField(
            model_name='team',
            name='dev',
        ),
        migrations.RemoveField(
            model_name='team',
            name='plan',
        ),
        migrations.AddField(
            model_name='team',
            name='jickgoons',
            field=models.ManyToManyField(to='gongmo.jickgoon'),
        ),
    ]
