# Generated by Django 4.2 on 2023-08-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0007_jickgoon_remove_team_design_remove_team_dev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jickgoon',
            name='capacity',
        ),
        migrations.AddField(
            model_name='jickgoon',
            name='design_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jickgoon',
            name='dev_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jickgoon',
            name='plan_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
