# Generated by Django 4.2 on 2023-08-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0008_remove_jickgoon_capacity_jickgoon_design_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jickgoon',
            name='name',
        ),
    ]
