# Generated by Django 4.2 on 2023-08-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0009_remove_jickgoon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='design',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='dev',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='plan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
