# Generated by Django 4.2 on 2023-08-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0010_team_design_team_dev_team_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='jickgoons',
        ),
        migrations.DeleteModel(
            name='Jickgoon',
        ),
    ]
