# Generated by Django 4.2 on 2023-08-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0011_remove_team_jickgoons_delete_jickgoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='design_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='dev_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='plan_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
