# Generated by Django 4.2 on 2023-08-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0013_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='jickgoon_type',
            field=models.CharField(blank=True, choices=[('dev', '개발'), ('plan', '기획'), ('design', '디자인')], max_length=50),
        ),
    ]
