# Generated by Django 4.2 on 2023-08-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0014_team_jickgoon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
