# Generated by Django 4.2 on 2023-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0017_remove_member_applicant_remove_member_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDingContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.URLField()),
                ('field', models.CharField(max_length=255)),
                ('eligibility', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('sponsorship', models.CharField(max_length=255)),
                ('application_period', models.CharField(max_length=255)),
                ('prize_total', models.CharField(max_length=255)),
                ('prize_first', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('details', models.TextField()),
            ],
        ),
    ]
