# Generated by Django 4.2 on 2023-08-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0018_ddingcontest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DDingContest',
        ),
        migrations.AddField(
            model_name='contest',
            name='isSchool',
            field=models.BooleanField(default=False),
        ),
    ]
