# Generated by Django 4.2 on 2023-08-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0019_delete_ddingcontest_contest_isschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='photo',
            field=models.TextField(),
        ),
    ]
