# Generated by Django 4.2 on 2023-08-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0020_alter_contest_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tendency',
            field=models.JSONField(default=list),
        ),
    ]
