# Generated by Django 4.2 on 2023-08-21 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gongmo', '0025_character_course_hobby_mbti_workingtime_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='MBTI',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='character',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='hoby',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='workingTime',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='characters',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='courses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hobbies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mtbi',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='workingTimes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jickgoon_type',
            field=models.CharField(choices=[('개발', '개발'), ('기획', '기획'), ('디자인', '디자인')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='MBTI',
        ),
        migrations.DeleteModel(
            name='WorkingTime',
        ),
    ]
