# Generated by Django 4.2 on 2023-08-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0026_remove_userinfo_mbti_remove_userinfo_character_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='mtbi',
            new_name='mbti',
        ),
    ]
