# Generated by Django 4.2.4 on 2023-08-21 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gongmo', '0027_rename_mtbi_userinfo_mbti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='jickgoon_type',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='mbti',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='workingTimes',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dream',
            field=models.TextField(default='developer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hobby',
            field=models.TextField(default='coding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='job',
            field=models.TextField(default='developer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='major',
            field=models.CharField(default='computer-science', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='nick', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tendency_MBTI',
            field=models.CharField(default='ESTJ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tendency_personality',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tendency_worktime',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('job', models.JSONField(blank=True, null=True)),
                ('hobby', models.JSONField(blank=True, null=True)),
                ('dream', models.JSONField(blank=True, null=True)),
                ('tendency_worktime', models.CharField(max_length=100)),
                ('tendency_personality', models.JSONField(blank=True, null=True)),
                ('tendency_MBTI', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
