# Generated by Django 4.2.4 on 2023-08-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0028_remove_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='call',
            field=models.TextField(default='010-5253-4157'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='introduce',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='languages_tools',
            field=models.TextField(default='JAVA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='portfolio',
            field=models.TextField(default='likelion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='type_message',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='call',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='introduce',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages_tools',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_message',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
