# Generated by Django 4.2.4 on 2023-08-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongmo', '0029_userinfo_call_userinfo_introduce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='seoyeon', max_length=100),
            preserve_default=False,
        ),
    ]
