# Generated by Django 4.2 on 2023-08-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('type_src', models.TextField()),
                ('type_message', models.TextField()),
                ('type_hashtage', models.TextField()),
                ('type_explain1', models.TextField()),
                ('type_explain2', models.TextField()),
                ('type_explain3', models.TextField()),
                ('type_explain4', models.TextField()),
                ('type_best', models.CharField(max_length=255)),
                ('type_best_message', models.TextField()),
                ('type_best_src', models.TextField()),
                ('type_worst', models.CharField(max_length=255)),
                ('type_worst_message', models.TextField()),
                ('type_worst_src', models.TextField()),
            ],
        ),
    ]
