# Generated by Django 4.2 on 2023-08-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='type_hashtage',
            new_name='type_hastage',
        ),
    ]
