# Generated by Django 4.2 on 2023-08-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='nickname',
        ),
    ]
