# Generated by Django 4.2 on 2023-08-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_rename_type_hashtage_character_type_hastage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='type_hastage',
            new_name='type_hashtag',
        ),
    ]
