# Generated by Django 4.2 on 2023-08-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_mycharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
