# Generated by Django 4.2 on 2023-08-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_character_typeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='typeId',
        ),
    ]
